routes/login.py
from flask import Blueprint, render_template, redirect, url_for, flash, session, request
from werkzeug.security import generate_password_hash, check_password_hash
from forms import LoginForm, CadastroUsuarioForm
from db import get_db_connection, criar_usuario
from usuario import Usuario
auth = Blueprint('auth', __name__)


@auth.route('/')
def home():
    if 'usuario_logado' in session:
        return render_template('Registro/home.html')
    else:
        return redirect(url_for('auth.login'))

@auth.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if 'usuario_logado' in session:
        return redirect(url_for('auth.home'))
    if form.validate_on_submit():
        usuario = form.usuario.data
        senha = form.senha.data
        user, senha_hash = Usuario.buscar_por_nome(usuario)
        if user and check_password_hash(senha_hash, senha):
            session['usuario_logado'] = {'id': user.id, 'nome': user.usuario, 'email': user.email}
            flash('Login realizado com sucesso!', 'success')
            return redirect(url_for('auth.home'))
        else:
            flash('Usuário ou senha incorretos.', 'danger')
    return render_template('Registro/login.html', form=form)

@auth.route('/logout/')
def logout():
    session.pop('usuario_logado', None)
    flash('Você saiu do sistema.', 'info')
    return redirect(url_for('auth.login'))

@auth.route('/registrar', methods=['GET', 'POST'])
def registrar():
    if 'usuario_logado' in session:
        return redirect(url_for('auth.home'))
    form = CadastroUsuarioForm()
    if form.validate_on_submit():
        usuario = form.usuario.data
        email = form.email.data
        senha = form.senha.data
        tipo = 'xxx'
        try:
            Usuario.criar(usuario,senha,email,tipo)
            flash('Usuário registrado com sucesso!', 'success')
            return redirect(url_for('auth.login'))
        except Exception as e:
            flash('Erro ao registrar usuário.', 'danger')
    return render_template('Registro/register.html', form=form)

templates/Registro/home.html
{% extends 'base.html' %}
{% block title %}Home{% endblock %}
{% block content %}
<main class="form-signin w-100 m-auto" style="padding:15px;">
  <!-- wrapper flexível: gap-3 dá espaçamento lateral entre os cards -->
  <div class="d-flex justify-content-center gap-3 flex-wrap">
    <!-- Card 1 -->
    <div class="card" style="width:18rem;">
      <div class="card-body">
        <h5 class="card-title">ECAC</h5>
        <p class="card-text">
          Portal e-CAC. ACESSO GOVBR. versão clássica Receita Federal.
        </p>
        <a href="https://cav.receita.fazenda.gov.br/autenticacao/login" class="btn btn-primary">Link</a>
      </div>
    </div>
    <!-- Card 2 -->
    <div class="card" style="width:18rem;">
      <div class="card-body">
        <h5 class="card-title">CND Federal</h5>
        <p class="card-text">
          Certidão de Débitos Relativos a Créditos Tributários Federais e à Dívida Ativa da União
        </p>
        <a href="https://solucoes.receita.fazenda.gov.br/servicos/certidaointernet/pj/emitir" class="btn btn-primary">Link</a>
      </div>
    </div>
    <!-- Card 3 -->
    <div class="card" style="width:18rem;">
      <div class="card-body">
        <h5 class="card-title">CRF</h5>
        <p class="card-text">
          Consulta Regularidade do Empregador
        </p>
        <a href="https://consulta-crf.caixa.gov.br/consultacrf/pages/consultaEmpregador.jsf" class="btn btn-primary">Link</a>
      </div>
    </div>
{% endblock %}

templates/Registro/login.html
{% extends 'base.html' %}
{% block title %}Login{% endblock %}
{% block content %}
<main class="form-signin w-100 m-auto" style="max-width: 400px; padding: 15px;">
  <form method="POST" action="{{ url_for('auth.login') }}">
        {{ form.hidden_tag() }}
        <p>
            {{ form.usuario.label }}<br>
            {{ form.usuario(class="form-control", id="usuario", placeholder="Usuário") }}
        </p>
        <p>
            {{ form.senha.label }}<br>
            {{ form.senha(class="form-control", id="senha", placeholder="Senha") }}
        </p>
        <p>{{ form.submit(class="w-100 btn btn-lg btn-primary") }}</p>
  </form>
<div class="mt-3 text-center">
    <a class="btn btn-outline-secondary w-100" href="{{ url_for('auth.registrar') }}">Registrar</a>
</div>
</main>
{% endblock %}

templates/Registro/register.html
{% extends 'base.html' %}

{% block title %}Registrar{% endblock %}

{% block content %}
<main class="form-signin w-100 m-auto" style="max-width: 400px; padding: 15px;">
  <form method="POST" action="{{ url_for('auth.registrar') }}">
    {{ form.hidden_tag() }}

    <p>
        {{ form.usuario.label }}<br>
        {{ form.usuario(class="form-control", id="usuario", placeholder="Usuário") }}
    </p>

    <p>
        {{ form.email.label }}<br>
        {{ form.email(class="form-control", id="email", placeholder="Email") }}
    </p>

    <p>
        {{ form.senha.label }}<br>
        {{ form.senha(class="form-control", id="senha", placeholder="Senha") }}
    </p>

    <p>{{ form.submit(class="w-100 btn btn-lg btn-primary") }}</p>
</form>

</main>
{% endblock %}