routes/perfil.py
from flask import Blueprint, render_template, redirect, url_for, flash, session, request
from werkzeug.security import generate_password_hash, check_password_hash
from routes.modulos.requisito_login import login_requisito
from forms import LoginForm, Editar_usuario, Deletar_usuario_botao, Trocar_senha_usuario
from db import editar_usuario,dados_usuario_id, deletar_usuario as _deletar_usuario
from usuario import Usuario
perfil = Blueprint('perfil', __name__)

@perfil.route('/meu_perfil', methods=['GET', 'POST'])
@login_requisito
def meu_perfil():
    usuario = Usuario.buscar_por_id(session['usuario_logado']['id'])
    form = Editar_usuario()
    formDel = Deletar_usuario_botao()
    if form.validate_on_submit():
        usuario_nome = form.usuario.data
        email = form.email.data
        flash('Dados do perfil editados com sucesso', 'success')
        usuario.atualizar(usuario_nome, email)
        return redirect(url_for('auth.home'))
    if formDel.validate_on_submit():
        return redirect(url_for('auth.login'))
    return render_template('perfil/meu_perfil.html' ,usuario=usuario, form=form)



@perfil.route('/trocar_senha', methods=['GET', 'POST'])
@login_requisito
def trocar_senha():
    usuario_obj = Usuario.buscar_por_id(session['usuario_logado']['id'])
    formsenha = Trocar_senha_usuario()
    if formsenha.validate_on_submit():
        senha = formsenha.senha.data
        usuario_obj.trocar_senha(senha)
        flash('Senha trocada com sucesso!','success')
        return redirect(url_for('auth.login'))
    return render_template('perfil/trocar_senha.html' , form=formsenha)




@perfil.route('/deletar_usuario', methods=['GET', 'POST'])
@login_requisito
def deletar_usuario():
    usuario_obj = Usuario.buscar_por_id(session['usuario_logado']['id'])
    usuario_obj.deletar()
    return redirect('logout')

templates/perfil/meu_perfil.html
{% extends 'base.html' %}
{% block title %}Meu perfil{% endblock %}
{% block content %}

<div class="d-flex justify-content-center align-items-center" style="min-height: 80vh;">
  <div class="card p-4" style="width: 100%; max-width: 600px;">
    <div class="card-body">
      <h2 class="card-title text-center mb-4">Meu Perfil</h2>
      <form method="POST" action="{{ url_for('perfil.meu_perfil') }}" class="row g-3">
        {{ form.hidden_tag() }}
        <div class="col-md-6">
          {{ form.usuario.label(class="form-label") }}
          {{ form.usuario(class="form-control" ,value=usuario['usuario']) }}
        </div>
        <div class="col-12">
          {{ form.email.label(class="form-label") }}
          {{ form.email(class="form-control",value=usuario['email']) }}
        </div>
        <div class="col-12 text-center">
          {{ form.submit(class="btn btn-primary w-100") }}
        </div>
      </form>
      <form method="POST" action="{{ url_for('perfil.trocar_senha') }}">
        {{ form.hidden_tag() }}  <!-- CSRF token (use o mesmo form ou crie um DeleteForm) -->
        <button
          type="submit"
          class="btn btn-outline-secondary w-100 mt-3"
        >
          Trocar senha
        </button>

      </form>
       <!-- Botão de Deletar Usuário -->
      <form method="POST" action="{{ url_for('perfil.deletar_usuario') }}">
        {{ form.hidden_tag() }}  <!-- CSRF token (use o mesmo form ou crie um DeleteForm) -->
        <button
          type="submit"
          class="btn btn-danger w-100 mt-3"
          onclick="return confirm('Tem certeza que deseja apagar sua conta?');"
        >
          Deletar Usuário
        </button>
      </form>
  </div>
</div>
{% endblock %}

templates/perfil/trocar_senha.html
{% extends 'base.html' %}
{% block title %}Meu perfil{% endblock %}
{% block content %}

<div class="d-flex justify-content-center align-items-center" style="min-height: 80vh;">
  <div class="card p-4" style="width: 100%; max-width: 600px;">
    <div class="card-body">
      <h2 class="card-title text-center mb-4">Meu Perfil</h2>
      <form method="POST" action="{{ url_for('perfil.trocar_senha') }}" class="row g-3">
        {{ form.hidden_tag() }}
        <div class="col-md-12">
          {{ form.senha.label(class="form-label") }}
          {{ form.senha(class="form-control") }}
        </div>
        <div class="col-12 text-center">
          {{ form.submit(class="btn btn-primary w-100") }}
        </div>
      </form>
  </div>
</div>
{% endblock %}